version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imersao17
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    volumes:
      - .docker/mysql:/var/lib/mysql